- type: job
  id: HeadOfMedicalSector
  name: job-name-head-of-medical-sector
  description: job-description-head-of-medical-sector
  playTimeTracker: JobHeadOfMedicalSector
  requirements: # TODO: Поменять после того, как игроки наберут время на новых ролях
    - !type:OverallPlaytimeRequirement
      time: 108000 # 30 часов
  weight: 10
  startingGear: HeadOfMedicalSectorGear
  icon: JobHeadOfMedicalSector
  supervisors: job-supervisors-director
  canBeAntag: true
  radioBold: true
  displayWeight: 60
  accessGroups:
  - HeadOfMedicalSector
  special:
  - !type:AddComponentSpecial
    components:
    - type: CommandStaff
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Three
    - type: ScpAnnounceOnSpawn
      text: head-announce-on-spawn
      channels:
      - MedicalService
      includeJobName: true
    - type: Fear
      phobias:
      - Exoremophobia
      # Врачи не пугаются трупов, у них не будет некрофобии

- type: startingGear
  id: HeadOfMedicalSectorGear
  equipment:
    id: KeyCardHeadOfMedicalSector
    ears: ClothingHeadsetAltMedicalService
    belt: ClothingBeltMedicalFilled
    pocket2: HeadOfMedicalSectorPDA
  storage:
    back:
    - Flash
    - Telebaton
