- type: job
  id: ElectricalTechnicalSpecialist
  name: job-name-electrical-technical-specialist
  description: job-description-electrical-technical-specialist
  playTimeTracker: JobElectricalTechnicalSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: EngineeringTechnicalService
      time: 18000
  startingGear: ElectricalTechnicalSpecialistGear
  icon: JobElectricalTechnicalSpecialist
  supervisors: job-supervisors-chief-technical-specialist
  displayWeight: 10
  accessGroups:
  - ElectricalSpecialist
  special:
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Two
    - type: ScpRepairableCanSeeExamineHints

- type: startingGear
  id: ElectricalTechnicalSpecialistGear
  equipment:
    eyes: ClothingEyesGlassesMeson
    id: KeyCardElectricalTechnicalSpecialist
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineeringTechnicalService
    pocket2: ScpEngineeringPDA
