- type: job
  id: GeneralTechnicalSpecialist
  name: job-name-general-technical-specialist
  description: job-description-general-technical-specialist
  playTimeTracker: JobGeneralTechnicalSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: EngineeringTechnicalService
      time: 7200
  startingGear: GeneralTechnicalSpecialistGear
  icon: JobGeneralTechnicalSpecialist
  supervisors: job-supervisors-chief-technical-specialist
  displayWeight: 10
  accessGroups:
  - CommonEngineeringJob
  special:
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Two

- type: startingGear
  id: GeneralTechnicalSpecialistGear
  equipment:
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineeringTechnicalService
    id: KeyCardGeneralTechnicalSpecialist
    pocket2: ScpEngineeringPDA
