- type: job
  id: LeadTechnicalSpecialist
  name: job-name-lead-technical-specialist
  description: job-description-lead-technical-specialist
  playTimeTracker: JobLeadTechnicalSpecialist
  requirements:
    - !type:DepartmentTimeRequirement
      department: EngineeringTechnicalService
      time: 54000
  startingGear: LeadTechnicalSpecialistGear
  icon: JobLeadTechnicalSpecialist
  supervisors: job-supervisors-chief-technical-specialist
  displayWeight: 30
  accessGroups:
  - LeadTechnicalSpecialist
  special:
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Three

- type: startingGear
  id: LeadTechnicalSpecialistGear
  equipment:
    id: KeyCardLeadTechnicalSpecialist
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineeringTechnicalService
    pocket2: ScpEngineeringPDA
  storage:
    back:
    - ClothingOuterHardsuitEngineeringCompact
