- type: job
  id: TechnicalTrainee
  name: job-name-technical-trainee
  description: job-description-technical-trainee
  playTimeTracker: JobTechnicalTrainee
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 1800
  startingGear: TechnicalTraineeGear
  icon: JobTechnicalTrainee
  supervisors: job-supervisors-chief-technical-specialist
  canBeAntag: true
  displayWeight: 0
  accessGroups:
  - CommonEngineeringJob
  special:
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Two

- type: startingGear
  id: TechnicalTraineeGear
  equipment:
    id: KeyCardTechnicalTrainee
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineeringTechnicalService
    pocket1: BookEngineersHandbook
    pocket2: ScpEngineeringPDA
