- type: job
  id: Psychotherapist
  name: job-name-psychotherapist
  description: job-description-psychotherapist
  playTimeTracker: JobPsychotherapist
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 18000
  startingGear: PsychotherapistGear
  icon: JobPsychotherapist
  supervisors: job-supervisors-head-of-medical-sector
  displayWeight: 10  # Sunrise
  accessGroups:
  - CommonMedicalJob
  special:
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Two

- type: startingGear
  id: PsychotherapistGear
  equipment:
    shoes: ClothingShoesLeather
    id: KeyCardPsychotherapist
    ears: ClothingHeadsetMedicalService
    pocket2: ScpMedicalPDA
  storage:
    back:
    - RubberStampPsychologist
