- type: job
  id: SeniorMedicalSpecialist
  name: job-name-senior-medical-specialist
  description: job-description-senior-medical-specialist
  playTimeTracker: JobSeniorMedicalSpecialist
  requirements:
  - !type:DepartmentTimeRequirement
    department: MedicalService
    time: 54000
  startingGear: SeniorMedicalSpecialistGear
  icon: JobSeniorMedicalSpecialist
  supervisors: job-supervisors-head-of-medical-sector
  displayWeight: 35
  accessGroups:
  - SeniorMedicalSpecialist
  special:
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Three
    - type: Fear
      phobias:
      - Exoremophobia
      # Врачи не пугаются трупов, у них не будет некрофобии
    - type: ShowScp096FaceDamageHud

- type: startingGear
  id: SeniorMedicalSpecialistGear
  equipment:
    id: KeyCardSeniorMedicalSpecialist
    ears: ClothingHeadsetMedicalService
    eyes: ClothingEyesHudMedical
    pocket2: ScpMedicalPDA
  storage:
    back:
    - MedicatedSuture
    - RegenerativeMesh
