- type: job # Удалить. Заменён Научным Сотрудником
  id: AnomabiologyResearcher
  name: job-name-anomabiology-researcher
  description: job-description-anomabiology-researcher
  playTimeTracker: JobAnomabiologyResearcher
  requirements: # TODO: Поменять после того, как игроки наберут время на новых ролях
  - !type:OverallPlaytimeRequirement
    time: 28800 # 8 часов
  startingGear: AnomabiologyResearcherGear
  icon: JobAnomabiologyResearcher
  supervisors: job-supervisors-scientific-service-director
  displayWeight: 10
  accessGroups:
  - Scientist
  special:
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Two
    - type: Fear
      phobias:
      - Exoremophobia
      - Necrophobia
      proximityBlockerLevel: None
      seenBlockerLevel: None


- type: startingGear
  id: AnomabiologyResearcherGear
  equipment:
    ears: ClothingHeadsetScientificService
    id: KeyCardAnomabiologyResearcher
