- type: job
  id: AnomarchologyResearcher
  name: job-name-anomarchology-researcher
  description: job-description-anomarchology-researcher
  playTimeTracker: JobAnomarchologyResearcher
  requirements:
  - !type:DepartmentTimeRequirement
    department: ScientificService
    time: 18000
  startingGear: AnomarchologyResearcherGear
  icon: JobAnomarchologyResearcher
  supervisors: job-supervisors-scientific-service-director
  displayWeight: 10
  accessGroups:
  - Scientist
  special:
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Two
    - type: Fear
      phobias:
      - Exoremophobia
      - Necrophobia
      proximityBlockerLevel: None
      seenBlockerLevel: None
    - type: ShowScp096FaceDamageHud

- type: startingGear
  id: AnomarchologyResearcherGear
  equipment:
    ears: ClothingHeadsetScientificService
    id: KeyCardAnomarchologyResearcher
    pocket2: ScpResearchPDA
