- type: job
  id: JuniorResearcher
  name: job-name-junior-researcher
  description: job-description-junior-researcher
  playTimeTracker: JobJuniorResearcher
  startingGear: JuniorResearcherGear
  icon: JobJuniorResearcher
  supervisors: job-supervisors-scientific-service-director
  canBeAntag: true
  displayWeight: 0
  accessGroups:
  - JuniorResearcher
  special:
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Two
    - type: Fear
      phobias:
      - Exoremophobia
      - Necrophobia
      proximityBlockerLevel: None
      seenBlockerLevel: None
    - type: ShowScp096FaceDamageHud

- type: startingGear
  id: JuniorResearcherGear
  equipment:
    shoes: ClothingShoesColorWhite
    id: KeyCardJuniorResearcher
    ears: ClothingHeadsetScientificService
    pocket1: BookScientistsGuidebook
    pocket2: ScpResearchPDA
