- type: job
  id: LeadResearcher
  name: job-name-lead-researcher
  description: job-description-lead-researcher
  playTimeTracker: JobLeadResearcher
  requirements: # TODO: Поменять после того, как игроки наберут время на новых ролях
  - !type:OverallPlaytimeRequirement
    time: 54000 # 15 часов
  startingGear: LeadResearcherGear
  icon: JobLeadResearcher
  supervisors: job-supervisors-scientific-service-director
  displayWeight: 35
  accessGroups:
  - LeadResearcher
  special:
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Three
    - type: Fear
      phobias:
      - Exoremophobia
      - Necrophobia
      proximityBlockerLevel: None
      seenBlockerLevel: None

- type: startingGear
  id: LeadResearcherGear
  equipment:
    head: ClothingHeadHatBeretRND
    id: KeyCardLeadResearcher
    ears: ClothingHeadsetScientificService
    outerClothing: ClothingOuterCoatLabSeniorResearcher
  storage:
    back:
    - WeaponPistolCHIMP
    - ScpResearchPDA
