- type: job
  id: LeadResearcher
  name: job-name-lead-researcher
  description: job-description-lead-researcher
  playTimeTracker: JobLeadResearcher
  requirements:
  - !type:DepartmentTimeRequirement
    department: ScientificService
    time: 54000
  startingGear: LeadResearcherGear
  icon: JobLeadResearcher
  supervisors: job-supervisors-scientific-service-director
  displayWeight: 35
  accessGroups:
  - LeadResearcher
  special:
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Three
    - type: Fear
      phobias:
      - Exoremophobia
      - Necrophobia
      proximityBlockerLevel: None
      seenBlockerLevel: None
    - type: ShowScp096FaceDamageHud

- type: startingGear
  id: LeadResearcherGear
  equipment:
    head: ClothingHeadHatBeretRND
    id: KeyCardLeadResearcher
    ears: ClothingHeadsetScientificService
    outerClothing: ClothingOuterCoatLabSeniorResearcher
    pocket2: ScpResearchPDA
