- type: job
  id: ProductionSpecialist
  name: job-name-production-specialist
  description: job-description-production-specialist
  playTimeTracker: JobProductionSpecialist
  requirements: # TODO: Поменять после того, как игроки наберут время на новых ролях
    - !type:OverallPlaytimeRequirement
      time: 10800 # 3 часов
  startingGear: ProductionSpecialistGear
  icon: JobProductionSpecialist
  supervisors: job-supervisors-scientific-service-director
  displayWeight: 10
  accessGroups:
  - ProductionSpecialist
  special:
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Two
    - type: Fear
      phobias:
      - Exoremophobia
      - Necrophobia
      proximityBlockerLevel: None
      seenBlockerLevel: None
    - type: ShowScp096FaceDamageHud

- type: startingGear
  id: ProductionSpecialistGear
  equipment:
    ears: ClothingHeadsetScientificService
    id: KeyCardProductionSpecialist
    pocket2: ScpResearchPDA
