- type: job
  id: HeavyContainmentZoneCommandant
  name: job-name-heavy-containment-zone-commandant
  description: job-description-heavy-containment-zone-commandant
  playTimeTracker: JobHeavyContainmentZoneCommandant
  requirements:
  - !type:DepartmentTimeRequirement
    department: HeavyContainmentSecurityService
    time: 43200
  icon: JobHeavyContainmentZoneCommandant
  supervisors: job-supervisors-security-commander
  canBeAntag: false
  displayWeight: 70
  accessGroups:
  - SecurityCommandant
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Three
    - type: ScpAnnounceOnSpawn
      text: squad-commander-announce-on-spawn
      channels:
      - HeavyContainmentSecurityService
      includeJobName: true
    - type: SpeakOnEyeStateChange
      phraseOnClose:
      - close-eye-phrase-1
      - close-eye-phrase-2
      - close-eye-phrase-3
      - close-eye-phrase-4
      phraseOnOpen:
      - open-eye-phrase-1
      - open-eye-phrase-2
      - open-eye-phrase-3
      - open-eye-phrase-4
    - type: Fear # переопределение компонента страха для СБ
      phobias:
      - Exoremophobia
      - Necrophobia
      proximityBlockerLevel: None
      seenBlockerLevel: None
      fearBasedSpreadAngleModifier:
        Anxiety: 1.2
        Fear: 2
        Terror: 5
      fearBasedGrainStrength:
        None: 0
        Anxiety: 70
        Fear: 230
        Terror: 550
      fearBasedVignetteStrength:
        None: 0
        Anxiety: 30
        Fear: 60
        Terror: 350
      baseJitterTime: 2
      fallOffChance: 1

- type: startingGear
  id: HeavyContainmentZoneCommandantGear
  equipment:
    head: ClothingHeadHatCapLeatherSquadLeader
    ears: ClothingHeadsetAltHeavyContainmentSecurityService
    eyes: ClothingEyesGlassesSecurity
    neck: ClothingNeckMantleSecurity
    jumpsuit: ClothingUniformJumpsuitSquadLeader
    outerClothing: ClothingOuterArmorSecurity
    gloves: ClothingHandsGlovesColorBlackAlt
    shoes: ClothingShoesBootsSecurityGuard
    id: KeyCardHeavyContainmentZoneCommandant
    pocket2: ScpSecurityPDA
