- type: entity
  parent: [ClothingHandsGlovesColorBlack, BaseRestrictedContraband]
  id: ClothingHandsGlovesSecurity
  name: security gloves
  description: Regular black security gloves that do not keep you from frying.
  suffix: SCP Guard
  components:
  - type: Sprite
    sprite: _Scp/Clothing/Hands/black.rsi
  - type: Clothing
    sprite: _Scp/Clothing/Hands/black.rsi

- type: entity
  parent: [ClothingHandsGlovesColorBlack, BaseRestrictedContraband]
  id: ClothingHandsGlovesWinterSecurity
  name: winter security gloves
  description: Winter black security gloves that do not keep you from frying.
  suffix: SCP Guard
  components:
  - type: Sprite
    sprite: _Scp/Clothing/Hands/winter_black.rsi
  - type: Clothing
    sprite: _Scp/Clothing/Hands/winter_black.rsi
  - type: TemperatureProtection
    heatingCoefficient: 1.05
    coolingCoefficient: 0.85

- type: entity
  parent: [ClothingHandsGlovesColorBlack, BaseRestrictedContraband]
  id: ClothingHandsGlovesColorBlackAlt
  suffix: SCP Guard
  components:
  - type: Sprite
    sprite: _Scp/Clothing/Hands/glovesPathologist.rsi
  - type: Clothing
    sprite: _Scp/Clothing/Hands/glovesPathologist.rsi
