- type: entity
  id: LockerExternalAdministrativeZoneCommandantFilled
  suffix: Filled
  parent: LockerExternalAdministrativeZoneCommandant
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
      - id: ClothingHeadHatCapWardenAlt
      - id: ClothingBeltSecurityFilled
      - id: Flash
      - id: ClothingHeadsetAltExternalAdministrativeZoneSecurityService
      - id: ClothingEyesGlassesSecurityGuard
      - id: ClothingHandsGlovesCombat
      - id: ClothingShoesBootsSecurityGuard
      - id: ClothingOuterCoatWarden
      - id: ClothingOuterWinterWarden
      - id: ClothingOuterCoatWardenAlt
      - id: RubberStampWarden
      - id: DoorRemoteArmory
      - id: Binoculars
      - id: HyperLinkBookCorporateLaw
      - id: HandheldCriminalRecordsMonitor
      - id: PortableSurveillanceCameraMonitor
      # Добавлены "Детективные" вещи до добавления отдельного шкафчика/должности под эти дела.
      - id: ForensicScanner
      - id: BoxForensicPad
      - id: BoxEvidenceMarkers
      - id: HandLabeler

- type: entity
  id: LockerExternalAdministrativeZoneOfficerFilled
  suffix: Filled
  parent: LockerExternalAdministrativeZoneOfficer
  components:
  - type: StorageFill
    contents:
      - id: FlashlightSeclite
        prob: 0.8
      - id: ClothingUniformSecurity
        prob: 0.3
      - id: ClothingUniformSecurity2
        prob: 0.3
      - id: ClothingUniformSecurity3
        prob: 0.3
      - id: ClothingHeadHelmetSecurity
      - id: ClothingOuterArmorSecurity
      - id: ClothingBeltSecurityFilled
      - id: Flash
        prob: 0.5
      - id: ClothingEyesGlassesSecurityGuard
      - id: ClothingMaskSecurityBandBlack
      - id: ClothingHeadsetExternalAdministrativeZoneSecurityService
      - id: ClothingHandsGlovesSecurity
      - id: ClothingShoesBootsSecurityGuard
      - id: WeaponMeleeNeedle
        prob: 0.1
      - id: HyperLinkBookCorporateLaw
        prob: 0.5
