# Командир
- type: job
  id: MHLeader
  name: ghost-role-information-mtf-leader-MH-name
  description: ghost-role-information-mtf-leader-description
  playTimeTracker: JobMHLeader
  setPreference: false
  startingGear: MHLeaderGear
  icon: JobIconMHleader
  supervisors: ghost-role-information-mtf-leader-supervisors
  canBeAntag: false
  radioBold: true
  overrideConsoleVisibility: false
  alwaysShowInBanPanel: true
  accessGroups:
  - AllComplex
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: MHLeaderGear
  equipment:
    jumpsuit: ClothingUniformMH
    back: MtfTacticalBackpack
    shoes: ClothingShoesBootsNTFFilled
    mask: ClothingMaskGasMobileTaskForceMH
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHelmetMobileTaskForceMH
    gloves: ClothingHandsGlovesMobileTaskForceMH
    outerClothing: ClothingOuterArmorMobileTaskForceMH
    id: KeyCardMtfMHLeader
    ears: ClothingHeadsetAltMTF
    belt: ClothingBeltMtfSparePouch
    pocket1: BaseUplinkMTFLeader
    pocket2: MobileTaskForcePDA
  storage:
    back:
    - BoxMtfLeaderKit
    - Crowbar
    - HandheldCrewMonitor

# Специалист
- type: job
  id: MHSpecialist
  name: ghost-role-information-mtf-specialist-MH-name
  description: ghost-role-information-mtf-specialist-description
  playTimeTracker: JobMHSpecialist
  setPreference: false
  startingGear: MHSpecialistGear
  icon: JobIconMH
  supervisors: ghost-role-information-mtf-specialist-supervisors
  canBeAntag: false
  overrideConsoleVisibility: false
  alwaysShowInBanPanel: true
  accessGroups:
  - AllComplex
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: MHSpecialistGear
  equipment:
    jumpsuit: ClothingUniformMH
    back: MtfTacticalBackpack
    shoes: ClothingShoesBootsNTFFilled
    mask: ClothingMaskGasMobileTaskForceMH
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHelmetMobileTaskForceMH
    gloves: ClothingHandsGlovesMobileTaskForceMH
    outerClothing: ClothingOuterArmorMobileTaskForceMH
    id: KeyCardMtfMHSpecialist
    ears: ClothingHeadsetAltMTF
    belt: ClothingBeltMtfSparePouch
    pocket1: BaseUplinkMTFSpecialist
    pocket2: MobileTaskForcePDA
  storage:
    back:
    - Crowbar
    - BoxMtfBaseKit

# Кадет
- type: job
  id: MHCadet
  name: ghost-role-information-mtf-cadet-MH-name
  description: ghost-role-information-mtf-cadet-description
  playTimeTracker: JobMHCadet
  setPreference: false
  startingGear: MHCadetGear
  icon: JobIconMH
  supervisors: ghost-role-information-mtf-cadet-supervisors
  canBeAntag: false
  overrideConsoleVisibility: false
  alwaysShowInBanPanel: true
  accessGroups:
  - AllComplex
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: MHCadetGear
  equipment:
    jumpsuit: ClothingUniformMH
    back: MtfTacticalBackpack
    shoes: ClothingShoesBootsNTFFilled
    mask: ClothingMaskGasMobileTaskForceMH
    eyes: ClothingEyesGlassesSecurity
    head: ClothingHelmetMobileTaskForceMH
    gloves: ClothingHandsGlovesMobileTaskForceMH
    outerClothing: ClothingOuterArmorMobileTaskForceMH
    id: KeyCardMtfMHCadet
    ears: ClothingHeadsetAltMTF
    belt: ClothingBeltMtfSparePouch
    pocket1: BaseUplinkMTFCadet
    pocket2: MobileTaskForcePDA
  storage:
    back:
    - Crowbar
    - BoxMtfBaseKit
