# Командир
- type: job
  id: NTFLeader
  name: ghost-role-information-mtf-leader-NTF-name
  description: ghost-role-information-mtf-leader-description
  playTimeTracker: JobNTFLeader
  setPreference: false
  startingGear: NTFLeaderGear
  icon: JobIconNTFleader
  supervisors: ghost-role-information-mtf-leader-supervisors
  canBeAntag: false
  radioBold: true
  overrideConsoleVisibility: false
  alwaysShowInBanPanel: true
  accessGroups:
  - AllComplex
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: NTFLeaderGear
  equipment:
    jumpsuit: ClothingUniformNTF
    back: MTFTacticalBackpack
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHelmetMTFTactical
    mask: ClothingMaskMTF
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorTactical
    id: KeyCardMtfNTFLeader
    ears: ClothingHeadsetAltMTF
    belt: ClothingBeltMTFSparePouch
    pocket1: BaseUplinkMTFLeader
    pocket2: PouchAmmo
  storage:
    back:
    - BoxMRE
    - Crowbar
    - HandheldCriminalRecordsMonitorUnpowered
    - DoubleEmergencyOxygenTankFilled
    - HandheldCrewMonitor
    - MobileTaskForcePDA
    belt:
    - Stunbaton
    - Handcuffs
    - Handcuffs
    - Handcuffs

# Специалист
- type: job
  id: NTFSpecialist
  name: ghost-role-information-mtf-specialist-NTF-name
  description: ghost-role-information-mtf-specialist-description
  playTimeTracker: JobNTFSpecialist
  setPreference: false
  startingGear: NTFSpecialistGear
  icon: JobIconNTF
  supervisors: ghost-role-information-mtf-specialist-supervisors
  canBeAntag: false
  overrideConsoleVisibility: false
  alwaysShowInBanPanel: true
  accessGroups:
  - AllComplex
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: NTFSpecialistGear
  equipment:
    jumpsuit: ClothingUniformNTF
    back: MTFTacticalBackpack
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHelmetMTFTactical
    mask: ClothingMaskMTF
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorTactical
    id: KeyCardMtfNTFSpecialist
    ears: ClothingHeadsetAltMTF
    belt: ClothingBeltMTFSparePouch
    pocket1: BaseUplinkMTFSpecialist
    pocket2: PouchAmmo
  storage:
    back:
    - Crowbar
    - DoubleEmergencyOxygenTankFilled
    - BoxMRE
    - MobileTaskForcePDA
    belt:
    - Stunbaton
    - Handcuffs
    - Handcuffs
    - Handcuffs

# Кадет
- type: job
  id: NTFCadet
  name: ghost-role-information-mtf-cadet-NTF-name
  description: ghost-role-information-mtf-cadet-description
  playTimeTracker: JobNTFCadet
  setPreference: false
  startingGear: NTFCadetGear
  icon: JobIconNTF
  supervisors: ghost-role-information-mtf-cadet-supervisors
  canBeAntag: false
  overrideConsoleVisibility: false
  alwaysShowInBanPanel: true
  accessGroups:
  - AllComplex
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: NTFCadetGear
  equipment:
    jumpsuit: ClothingUniformNTF
    back: MTFTacticalBackpack
    shoes: ClothingShoesBootsJackFilled
    head: ClothingHelmetMTFTactical
    mask: ClothingMaskMTF
    eyes: ClothingEyesGlassesSecurity
    gloves: ClothingHandsGlovesCombat
    outerClothing: ClothingOuterArmorScout
    id: KeyCardMtfNTFCadet
    ears: ClothingHeadsetAltMTF
    belt: ClothingBeltMTFSparePouch
    pocket1: BaseUplinkMTFCadet
    pocket2: PouchAmmo
  storage:
    back:
    - Crowbar
    - DoubleEmergencyOxygenTankFilled
    - BoxMRE
    - MobileTaskForcePDA
    belt:
    - Stunbaton
    - Handcuffs
    - Handcuffs
    - Handcuffs
