- type: job
  id: FieldMedicalSpecialist
  name: job-name-field-medical-specialist
  description: job-description-field-medical-specialist
  playTimeTracker: JobFieldMedicalSpecialist
  requirements:
  - !type:DepartmentTimeRequirement
    department: ExternalAdministrativeZoneSecurityService
    time: 10800
  - !type:DepartmentTimeRequirement
    department: MedicalService
    time: 10800
  startingGear: FieldMedicalSpecialistGear
  icon: JobAmnesthesiologist
  supervisors: job-supervisors-heavy-containment-zone-commandant
  canBeAntag: false
  displayWeight: 15
  accessGroups:
  - FieldMedic
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Three
    - type: Fear
      phobias:
      - Exoremophobia
      # Врачи не пугаются трупов, у них не будет некрофобии

- type: startingGear
  id: FieldMedicalSpecialistGear
  equipment:
    outerClothing: ClothingOuterCoatLabSecurityMedic
    shoes: ClothingShoesColorRed
    gloves: ClothingHandsGlovesLatex
    eyes: ClothingEyesHudMedSec
    head: ClothingHeadHatBeretSecurityMedic
    id: KeyCardFieldMedicalSpecialist
    ears: ClothingHeadsetFieldMedicalSpecialist
    belt: ClothingBeltMedicalFilled
    pocket1: AmnesiacSpray
    pocket2: ScpMedicalPDA
  storage:
    back:
    - Flash
