- type: job
  id: JuniorExternalAdministrativeZoneOfficer
  name: job-name-junior-external-administrative-zone-officer
  description: job-description-junior-external-administrative-zone-officer
  playTimeTracker: JobJuniorExternalAdministrativeZoneOfficer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 18000
  icon: JobJuniorExternalAdministrativeZoneOfficer
  supervisors: job-supervisors-external-administrative-zone-commandant
  canBeAntag: false
  displayWeight: 0
  accessGroups:
  - SecurityJobCommon
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: Three
    - type: SpeakOnEyeStateChange # переопределение моргания с другими параметрами для охраны и МОГа
      # Часть фраз уходит, так как более разговорная. А эти парни натренированы.
      phraseOnClose:
      - close-eye-phrase-1
      - close-eye-phrase-3
      - close-eye-phrase-4
      phraseOnOpen:
      - open-eye-phrase-1
      - open-eye-phrase-3
      speakOnlyInScp173Chamber: false
    - type: Fear # переопределение компонента страха для СБ
      phobias:
      - Exoremophobia
      - Necrophobia
      proximityBlockerLevel: None
      seenBlockerLevel: None
      fearBasedSpreadAngleModifier:
        Anxiety: 1.7
        Fear: 2.2
        Terror: 5
      baseJitterTime: 3
      fallOffChance: 2

- type: startingGear
  id: JuniorExternalAdministrativeZoneOfficerGear
  equipment:
    mask: ClothingMaskSecurityBandBlack
    id: KeyCardJuniorLightContainmentZoneSecurityOfficer
    ears: ClothingHeadsetExternalAdministrativeZoneSecurityService
    pocket1: HyperLinkBookCorporateLaw
    pocket2: ScpSecurityPDA
  storage:
    back:
    - Flash
