- type: job
  id: BotanistPhytogeneticist
  name: job-name-botanist-phytogeneticist
  description: job-description-botanist-phytogeneticist
  playTimeTracker: JobBotanistPhytogeneticist
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 3600
  startingGear: BotanistPhytogeneticistGear
  icon: JobBotanistPhytogeneticist
  supervisors: job-supervisors-personnel-officer
  access:
  - Service
  special:
  - !type:GiveItemOnHolidaySpecial
    holiday: FourTwenty
    prototype: CannabisSeeds
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: One

- type: startingGear
  id: BotanistPhytogeneticistGear
  equipment:
    shoes: ClothingShoesColorBrown
    id: KeyCardBotanistPhytogeneticist
    ears: ClothingHeadsetFoodAndSanitation
    belt: ClothingBeltPlantFilled
    pocket2: ScpServicePDA
