- type: job
  id: GastronomicSpecialist
  name: job-name-gastronomic-specialist
  description: job-description-gastronomic-specialist
  playTimeTracker: JobGastronomicSpecialist
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 3600
  startingGear: GastronomicSpecialistGear
  icon: JobGastronomicSpecialist
  supervisors: job-supervisors-personnel-officer
  access:
  - Service
  special:
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: One

- type: startingGear
  id: GastronomicSpecialistGear
  equipment:
    shoes: ClothingShoesColorBlack
    id: KeyCardGastronomicSpecialist
    ears: ClothingHeadsetFoodAndSanitation
    belt: ClothingBeltChefFilled
    pocket2: ScpServicePDA
