- type: job
  id: ServicePersonnel
  name: job-name-service-personnel
  description: job-description-service-personnel
  playTimeTracker: JobServicePersonnel
  startingGear: ServicePersonnelGear
  icon: JobServicePersonnel
  supervisors: job-supervisors-personnel-officer
  access:
  - Service
  special:
  - !type:AddComponentSpecial
    components:
    - type: EmployeeClass
      class: C
    - type: AccessLevel
      level: One

- type: startingGear
  id: ServicePersonnelGear
  equipment:
    shoes: ClothingShoesGaloshes
    id: KeyCardServicePersonnel
    ears: ClothingHeadsetFoodAndSanitation
    belt: ClothingBeltJanitorFilled
  storage:
    back:
    - ScpServicePDA
